### ISSUE TITLE
not an issue but idk where else to contact you

### ISSUE THREAD

**Issue by Hungerff** [sigson/UTanks#3]
hey man, love this project. i was just wondering if you ever thought pf making a unity version of the alternativa editor to make maps because the current one sucks so much. im asking because i saw you use the xml files for this project's maps

**Comment by sigson** [comment]
I didn’t rule out this option, but the most you can take from here is an XML file loader.  For the rest, it is better to use, for example, this asset https://assetstore.unity.com/packages/tools/modeling/runtime-editor-64806?srsltid=AfmBOorDoAJNZPPUMrAehMHwxOF9394SuSuv4DooHXjDe-qLa10PVFaU and build an editor around it.  This asset can be found free of charge for non-commercial use on various sites with addons, so if you set out to make a unity editor, in my opinion it is better to act this way than to write from scratch.

**Comment by Hungerff** [comment]
👍thx
