### ISSUE TITLE
Can't open utanksserver.exe; it opens and closes immediately, and I can't run the game either.

### ISSUE THREAD

**Issue by szammm** [sigson/UTanks#7]
Hello, please help me. I'm trying to run a game in Unity, and I followed all the instructions (moving the Data folder to the same folder as utanksserver.exe and then running the game). However, when I run the game, it throws the error 'Something went wrong during running the game,' and also, utanksserver.exe does not work; it opens and closes immediately. Sorry, I’m not sure what’s wrong.

**Comment by sigson** [comment]
> Hello, please help me. I'm trying to run a game in Unity, and I followed all the instructions (moving the Data folder to the same folder as utanksserver.exe and then running the game). However, when I run the game, it throws the error 'Something went wrong during running the game,' and also, utanksserver.exe does not work; it opens and closes immediately. Sorry, I’m not sure what’s wrong.

Maybe it help you.
[Youtube](https://youtu.be/QRVJT3mMJb0)

**Comment by szammm** [comment]
Did everything as shown in the video and it worked, thank you!

**Comment by szammm** [comment]
Did everything as shown in the video and it worked, thank you!
